typography_spectrum: 0.5605382823799322
color:
  brandStrength: 0.11120780092783936
  lightness: 0.3031727781440915
  saturation: 0.794080272581668
  rhythmicContrast: 0.2620798676057101
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
github: true
layout_spectrum: 0.1361749433222605
author:
  name: Fraser Stevenson
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6363c2dc-d1f8-4b3d-a6f2-ccd097cd6f6b.png
name: 7 Green
url: 'http://7-green.com'
title: Living Green Solutions
content: []
description: >-
  Since 2006 7 Green has been providing professional interior landscaping
  services including interior plant design & maintenance, office plant rental &
  care
purpose:
  - type: contact
    url: 'mailto:plants@7-green.com'
    label: Contact us
