typography_spectrum: 0.6413185883365056
color:
  brandStrength: 0.10471268027633576
  lightness: 0.7219920997708889
  saturation: 0.5848973039438081
  rhythmicContrast: 0.03982675492293247
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
github: true
layout_spectrum: 0.6791670968265522
author:
  name: Fraser Stevenson
  url: 'http://7-green.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0c929f6d-72e2-4000-96c4-b69503acac75.png
name: 7 Green
url: 'http://7-green.com'
navigation:
  - name: 'Hello, I''m Harinda'
    id: 617737fd-c13a-4a59-b791-d9a17a420b34
    type: content
  - name: Residential Landscaping
    id: 84b04e1a-6100-4aea-a173-c4835560ad42
    type: content
  - name: 'Commercial Landscaping '
    id: 61446445-7db0-4dbd-b50e-7a744b570c6b
    type: content
  - name: Commercial Maintenance Programs
    id: 2041de09-d5d2-45cc-b1b2-52c2b2e74395
    type: content
  - name: Sustainability
    id: 743a49e0-11a0-4f58-a0df-5d9cb11a65a7
    type: content
  - name: Contact Us
    id: acebc1e2-d1fe-4b3f-9ec1-59daf6bdd976
    type: content
title: 7-Green Living Solutions
content: []
description: Simply beautiful green spaces designed installed and maintained with care
purpose:
  - type: contact
    url: 'mailto:plants@7-green.com'
    label: Contact us
